FROM openjdk:8
COPY . /var/lib/jenkins/workspace/Jenkins docker integration/
WORKDIR /var/lib/jenkins/workspace/Jenkins docker integration/
RUN [ "javac", "JavaExample.java" ]
ENTRYPOINT [ "java", "JavaExample.java"]
