FROM openjdk:8
COPY  . C:/ProgramData/Jenkins/.jenkins/workspace/jenkins docker integration/src/java
WORKDIR C:/ProgramData/Jenkins/.jenkins/workspace/jenkins docker integration/src/java
RUN [ "javac", "JavaExample.java" ]
ENTRYPOINT [ "java", "JavaExample.java"]
