FROM openjdk:8
COPY . C:/ProgramData/Jenkins/.jenkins/workspace/Jenkinsdockerintegration/java
WORKDIR C:/ProgramData/Jenkins/.jenkins/workspace/Jenkinsdockerintegration/java
RUN javac JavaExample.java
CMD ["java","JavaExample"]

